const db = require('../DB_config/db');

const AI_SERVER = 'http://127.0.0.1:5001';

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/ai/forecasts
// Returns per-category forecasts generated by the Python model.
// Regenerates automatically if no valid forecasts exist.
// ─────────────────────────────────────────────────────────────────────────────
exports.getForecasts = async (req, res) => {
    try {
        const [rows] = await db.query(
            `SELECT * FROM hr_forecasts
             WHERE forecast_date >= CURRENT_DATE
               AND metric LIKE 'category_%'
             ORDER BY forecast_date ASC`
        );

        if (rows.length === 0) {
            // Nothing cached → generate fresh
            return exports.generateForecasts(req, res);
        }

        // Enrich cached rows with live current_staff so the UI 'Now' is always accurate
        const [liveCounts] = await db.query(`
            SELECT staff_category AS category, COUNT(*) AS current_staff
            FROM employees WHERE status = 'Active'
            GROUP BY staff_category
        `);
        const liveMap = Object.fromEntries(liveCounts.map(r => [r.category, parseInt(r.current_staff)]));

        const enriched = rows.map(row => {
            const cat = row.metric.replace('category_', '');
            const current = liveMap[cat] ?? 0;
            return {
                ...row,
                category:      cat,
                current_staff: current,
                gap:           parseInt(row.predicted_value) - current,
            };
        });

        return res.status(200).json(enriched);
    } catch (error) {
        console.error('getForecasts error:', error);
        res.status(500).json({ message: error.message });
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/ai/generate  (admin-only)
// Calls Python /forecast_by_category using live DB figures.
// ─────────────────────────────────────────────────────────────────────────────
exports.generateForecasts = async (req, res) => {
    try {
        console.log('Generating category-level AI Forecasts...');

        // 1. Pull live staff counts per category from employees table
        const [categoryCounts] = await db.query(`
            SELECT
                staff_category                              AS category,
                COUNT(*)                                    AS current_staff,
                AVG(TIMESTAMPDIFF(YEAR, date_of_joining, CURDATE())) AS avg_tenure,
                SUM(employment_type = 'Contract')           AS contract_staff
            FROM employees
            WHERE status = 'Active'
            GROUP BY staff_category
        `);

        if (categoryCounts.length === 0) {
            return res.status(400).json({ message: 'No active employees found.' });
        }

        // 2. Build payload for Python server
        //    Use realistic attrition rates for Ethiopian academic institutions
        const attritionByCategory = {
            Academic:       0.06,   // 6% p.a. – competitive external demand
            Technical:      0.05,
            Administrative: 0.04,
            Health:         0.07,   // nurses/doctors have high mobility
        };

        const payload = categoryCounts.map(row => ({
            category:          row.category,
            current_staff:     parseInt(row.current_staff),
            avg_age:           38 + (parseFloat(row.avg_tenure) || 0),  // heuristic
            contract_staff:    parseInt(row.contract_staff) || 0,
            low_performers:    Math.floor(parseInt(row.current_staff) * 0.04),
            predicted_attrition: attritionByCategory[row.category] || 0.05,
        }));

        // 3. Call Python AI server
        const aiResponse = await fetch(`${AI_SERVER}/forecast_by_category`, {
            method:  'POST',
            headers: { 'Content-Type': 'application/json' },
            body:    JSON.stringify(payload),
        });

        if (!aiResponse.ok) {
            const errText = await aiResponse.text();
            throw new Error(`AI Server error: ${errText}`);
        }

        const aiResults = await aiResponse.json();

        // 4. Persist to hr_forecasts (wipe old category forecasts first)
        await db.query(`DELETE FROM hr_forecasts WHERE metric LIKE 'category_%'`);

        const forecastDate = new Date();
        forecastDate.setFullYear(forecastDate.getFullYear() + 1);

        for (const r of aiResults) {
            const metricKey = `category_${r.category}`;
            await db.query(
                `INSERT INTO hr_forecasts (forecast_date, metric, predicted_value, confidence_score)
                 VALUES (?, ?, ?, ?)`,
                [forecastDate, metricKey, r.predicted_staff, r.confidence]
            );
        }

        // 5. Return enriched results
        const enriched = aiResults.map(r => ({
            metric:          `category_${r.category}`,
            category:        r.category,
            current_staff:   r.current_staff,
            predicted_value: r.predicted_staff,
            gap:             r.gap,
            confidence_score: r.confidence,
            forecast_date:   forecastDate,
        }));

        console.log('✅ Category forecasts generated:', enriched.map(e => `${e.category}: ${e.current_staff}→${e.predicted_value}`).join(', '));
        res.status(200).json(enriched);

    } catch (error) {
        console.error('generateForecasts error:', error);
        res.status(500).json({ message: error.message });
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/ai/rank-candidates/:vacancyId
// Ranks candidates using the Python logistic-regression model trained on
// academic metrics (CGPA, publications, teaching experience).
// ─────────────────────────────────────────────────────────────────────────────
exports.rankCandidates = async (req, res) => {
    try {
        const { vacancyId } = req.params;

        const [candidates] = await db.query(
            'SELECT * FROM candidates WHERE vacancy_id = ?',
            [vacancyId]
        );

        const [vacancies] = await db.query(
            'SELECT * FROM vacancies WHERE id = ?',
            [vacancyId]
        );
        const vacancy = vacancies[0];
        if (!vacancy) {
            return res.status(404).json({ message: 'Vacancy not found' });
        }

        if (candidates.length === 0) {
            return res.status(200).json([]);
        }

        const eduLevels = [
            "High School", "Diploma", "Bachelor's Degree",
            "Master's Degree", "PhD / Doctorate"
        ];

        // Determine minimum education for academic vs non-academic vacancy
        const isAcademic = vacancy.employment_type !== 'Administrative';
        const minEduIndex = isAcademic ? 3 : 2;  // Masters for academic, Bachelor's for admin

        const payload = candidates.map(c => {
            const eduIndex = eduLevels.indexOf(c.education_level);
            const educationMatch = eduIndex >= minEduIndex ? 1 : 0;
            const experienceGap = Math.max(0, (isAcademic ? 2 : 3) - (c.years_of_experience || 0));

            return {
                applicant_id:        c.id,
                applicant_name:      `${c.first_name} ${c.last_name}`,
                applicant_skills:    c.skills ? c.skills.split(',').map(s => s.trim()) : [],
                job_skills:          vacancy.requirements
                                        ? vacancy.requirements.split(',').map(s => s.trim())
                                        : ['communication', 'teamwork'],
                education_match:     educationMatch,
                experience_gap:      experienceGap,
                interview_score:     c.interview_score || 70,
                cgpa:                parseFloat(c.cgpa) || 0,
                publications:        parseInt(c.publications) || 0,
                teaching_experience: parseFloat(c.teaching_experience) || 0,
            };
        });

        const aiResp = await fetch(`${AI_SERVER}/rank_candidates`, {
            method:  'POST',
            headers: { 'Content-Type': 'application/json' },
            body:    JSON.stringify(payload),
        });

        if (!aiResp.ok) {
            throw new Error(`AI Server error: ${aiResp.statusText}`);
        }

        const ranked = await aiResp.json();

        // Enrich with candidate details
        const enriched = ranked.map(r => {
            const orig = payload.find(p => p.applicant_id === r.applicant_id);
            return {
                ...r,
                name:          orig?.applicant_name || 'Unknown',
                skills_matched: r.skill_score != null
                    ? `${(r.skill_score * 100).toFixed(0)}%`
                    : 'N/A',
                ai_score_pct:  `${(r.score * 100).toFixed(1)}%`,
            };
        });

        res.status(200).json(enriched);

    } catch (error) {
        console.error('rankCandidates error:', error);
        res.status(500).json({ message: error.message });
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/ai/turnover-risk
// Rule-based heuristic calibrated to TEDE campus staff categories.
// ─────────────────────────────────────────────────────────────────────────────
exports.getTurnoverRisk = async (req, res) => {
    try {
        const [employees] = await db.query(`
            SELECT id, first_name, last_name, role, department,
                   staff_category, employment_type, date_of_joining, gender
            FROM employees
            WHERE status = 'Active'
        `);

        const now = new Date();

        const atRisk = employees.map(emp => {
            let score = 0;
            const reasons = [];

            const yearsInService =
                (now - new Date(emp.date_of_joining)) / (1000 * 60 * 60 * 24 * 365.25);

            // ── Contract employment ──
            if (emp.employment_type === 'Contract') {
                score += 35;
                reasons.push('Contract appointment (high exit risk)');
            }

            // ── New hire window ──
            if (yearsInService < 0.75) {
                score += 15;
                reasons.push('Probationary period adjustment');
            }

            // ── Category-specific risks ──
            if (emp.staff_category === 'Academic') {
                if (yearsInService > 4 && emp.role.includes('Lecturer')) {
                    score += 30;
                    reasons.push('Lecturer stagnation (4+ yrs, no promotion signal)');
                }
                if (emp.department === 'Computer Science' || emp.department === 'Software Engineering' || emp.department === 'Information Technology') {
                    score += 20;
                    reasons.push('High private-sector demand for CS/IT skills');
                }
                if (emp.role.includes('Graduate Assistant')) {
                    score += 25;
                    reasons.push('Temporary graduate assistant – likely transitional');
                }
            }

            if (emp.staff_category === 'Health') {
                score += 20;
                reasons.push('Healthcare mobility – NGO & private sector pull');
                if (emp.role.includes('Nurse') && yearsInService > 3) {
                    score += 15;
                    reasons.push('Experienced nurse with external opportunities');
                }
            }

            if (emp.staff_category === 'Technical') {
                if (emp.employment_type === 'Contract' && yearsInService > 2) {
                    score += 20;
                    reasons.push('Long-serving contractor without permanent offer');
                }
            }

            if (emp.staff_category === 'Administrative') {
                if (yearsInService > 5 && emp.role.includes('Clerk')) {
                    score += 25;
                    reasons.push('Clerical stagnation – limited growth path');
                }
            }

            return {
                id:        emp.id,
                name:      `${emp.first_name} ${emp.last_name}`,
                role:      emp.role,
                department: emp.department,
                category:  emp.staff_category,
                riskScore: Math.min(score, 95),
                risk:      `${Math.min(score + Math.floor(Math.random() * 5), 95)}%`,
                reason:    reasons.length > 0 ? reasons.join(' • ') : 'Routine engagement monitoring',
            };
        })
        .filter(e => e.riskScore >= 40)
        .sort((a, b) => b.riskScore - a.riskScore)
        .slice(0, 6);

        res.status(200).json({ success: true, data: atRisk });

    } catch (error) {
        console.error('getTurnoverRisk error:', error);
        res.status(500).json({ message: error.message });
    }
};
